name: dieklingel-core
version: '0.0.1'
summary: Base Unit for dieKlinge
description: Base Unit for dieKlingel
confinement: devmode
base: core20
grade: stable

environment:
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/usr/lib:$SNAP/usr/lib:$SNAP/bin/lib

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: '3.3.10'
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      export PATH="$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter precache
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  gui:
    plugin: nil
    source: packages/gui
    after: [flutter-git]
    build-packages:
      - pkg-config
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    override-build: |
      set -eux
      flutter pub get
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/gui
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/gui/
  rtc:
    plugin: nil
    source: packages/rtc
    after: [flutter-git]
    build-packages:
      - pkg-config
    override-build: |
      set -eux
      flutter pub get
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/rtc
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/rtc/
  apn:
    plugin: nil
    source: packages/apn
    after: [flutter-git]
    override-build: |
      set -eux
      dart pub get
      dart compile exe bin/apn.dart -o apn
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/apn
      cp apn $SNAPCRAFT_PART_INSTALL/bin/apn/apn

apps:
  gui:
    command: bin/gui/gui
    daemon: simple
    passthrough:
      daemon-scope: user
    plugs:
      - home
      - network
    extensions: [gnome-3-38]
  rtc:
    command: bin/rtc/rtc
    daemon: simple
    passthrough:
      daemon-scope: user
    plugs:
      - home
      - network
      - camera
      - audio-playback
      - audio-record
    extensions: [gnome-3-38]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/bin/rtc/lib
  apn:
    command: bin/apn/apn
    daemon: simple
    passthrough:
      daemon-scope: user
    plugs:
      - home
      - network
