name: dieklingel-core
title: dieKlingel Core
contact: kai.mayer@dieklingel.com
website: https://dieklingel.de/
license: GPL-3.0
version: 0.0.2+3
summary: The core of the dieKlingel project.
description: The core project containing the most important services to run the door unit.
confinement: strict
compression: lzo
base: core22
grade: stable

architectures:
  # - build-on: amd64
  - build-on: arm64

apps:
  dieklingel-core:
    command: bin/core
    plugs:
      - wayland
      - network
      - camera
      - audio-playback
      - audio-record
    extensions:
      - gnome
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/bin/lib"
      DIEKLINGEL_HOME: "$SNAP_USER_COMMON"

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: '3.12.0'
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      export PATH="$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter precache
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  dieklingel-core:
    plugin: nil
    source: .
    after:
      - flutter-git
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      flutter clean
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - python3
