name: dieklingel-core
version: '0.0.1'
summary: Base Unit for dieKlinge
description: Base Unit for dieKlingel
confinement: strict
base: core22
grade: stable

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: '3.3.10'
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter precache
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  gui:
    plugin: nil
    source: packages/gui
    after: [flutter-git]
    build-packages:
      - pkg-config
    override-build: |
      set -eux
      flutter pub get || true
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/

apps:
  gui:
    command: bin/gui
    extensions: [gnome]
    