name: dieklingel
title: dieKlingel Core
contact: kai.mayer@dieklingel.com
website: https://dieklingel.de/
license: GPL-3.0
version: 0.0.2+3
summary: The core of the dieKlingel project.
description: The core project containing the most important services to run the door unit.
confinement: strict
base: core22
grade: stable

architectures:
  # - build-on: amd64
  - build-on: arm64

parts:
  core:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - curl
      - pkg-config
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev

apps:
  core:
    command: core
    plugs:
      - home
      - network
      - camera
      - audio-playback
      - audio-record
      - x11
      - wayland
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/bin/dieklingel_core/lib"
